# Generated by Django 4.2.7 on 2024-03-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
