# Generated by Django 4.2.7 on 2024-03-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_custom_user_otp_custom_user_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
