# Generated by Django 5.0.3 on 2024-03-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_custom_user_otp_remove_custom_user_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
