# Generated by Django 5.0.3 on 2024-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_custom_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='request_delete',
            field=models.BooleanField(default=False),
        ),
    ]
