# Generated by Django 5.0.3 on 2024-03-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_custom_user_request_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
