from django.contrib import admin
from .models import *
from .sound_models import *

admin.site.register(IT_WebsiteLogo)
admin.site.register(IT_WebsiteBanner)
admin.site.register(IT_CardHomepageTwoOne)
admin.site.register(IT_CardHomepageTwo)
admin.site.register(IT_CardHomepageThreeOne)
admin.site.register(IT_CardHomepageThreeTwo)
admin.site.register(IT_CardHomepageThree)
admin.site.register(IT_CardHomepageFourOne)
admin.site.register(IT_CardHomepageFourTwo)
admin.site.register(IT_CardHomepageFourThree)
admin.site.register(IT_CardHomepageFour)
admin.site.register(IT_CardTemplate)
admin.site.register(IT_BlogCard)
admin.site.register(IT_TimeData)
admin.site.register(IT_Homepage_Segment)
admin.site.register(IT_Support_Company_Logo)
admin.site.register(IT_Office_Address_1)
admin.site.register(IT_Office_Address_2)
admin.site.register(IT_Payment_Logo)
admin.site.register(IT_Social_Media)
admin.site.register(IT_Global_Location)
admin.site.register(IT_Contact_Us)
admin.site.register(IT_Subscriptions)
admin.site.register(IT_Footer_Section_1)
admin.site.register(IT_Footer_Section_1_Topics)
admin.site.register(IT_Footer_Section_2)
admin.site.register(IT_Footer_Section_2_Topics)
admin.site.register(IT_Footer_Section_3)
admin.site.register(IT_Footer_Section_3_Topics)
admin.site.register(IT_Technology)
admin.site.register(IT_Technology_Icon)
admin.site.register(IT_Our_Services)
admin.site.register(IT_Notice_Board)
admin.site.register(IT_Order_Card)
admin.site.register(IT_Security_Page)
admin.site.register(IT_Company_Member)



admin.site.register(IT_Live_Chat_Admin_Sound)
admin.site.register(IT_User_Sound)
admin.site.register(IT_User_Order_Sound)

