# Generated by Django 3.2.12 on 2024-03-02 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_User',
            fields=[
                ('custom_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.custom_user')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Sub-Admin', 'Sub-Admin')], max_length=50, null=True)),
                ('is_ti', models.BooleanField(default=False)),
                ('is_civil', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.custom_user',),
        ),
        migrations.CreateModel(
            name='Admin_User_Authentication_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_url', models.URLField(blank=True, null=True)),
                ('otp', models.CharField(max_length=6)),
                ('token', models.CharField(max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_authentication', to='admin_user.admin_user')),
            ],
        ),
    ]
