# Generated by Django 5.0.3 on 2024-03-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0003_rename_user_admin_otp_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_otp',
            name='otp_type',
            field=models.CharField(blank=True, choices=[('Password', 'Password'), ('Login', 'Login')], default='Login', max_length=50, null=True),
        ),
    ]
