from django.contrib import admin
from .models import *
from .sound_models import *

admin.site.register(Civil_WebsiteLogo)
admin.site.register(Civil_WebsiteBanner)
admin.site.register(Civil_CardHomepageTwoOne)
admin.site.register(Civil_CardHomepageTwo)
admin.site.register(Civil_CardHomepageThreeOne)
admin.site.register(Civil_CardHomepageThreeTwo)
admin.site.register(Civil_CardHomepageThree)
admin.site.register(Civil_CardHomepageFourOne)
admin.site.register(Civil_CardHomepageFourTwo)
admin.site.register(Civil_CardHomepageFourThree)
admin.site.register(Civil_CardHomepageFour)
admin.site.register(Civil_CardTemplate)
admin.site.register(Civil_BlogCard)
admin.site.register(Civil_TimeData)
admin.site.register(Civil_Homepage_Segment)
admin.site.register(Civil_Support_Company_Logo)
admin.site.register(Civil_Office_Address_1)
admin.site.register(Civil_Office_Address_2)
admin.site.register(Civil_Payment_Logo)
admin.site.register(Civil_Social_Media)
admin.site.register(Civil_Global_Location)
admin.site.register(Civil_Contact_Us)
admin.site.register(Civil_Subscriptions)
admin.site.register(Civil_Footer_Section_1)
admin.site.register(Civil_Footer_Section_1_Topics)
admin.site.register(Civil_Footer_Section_2)
admin.site.register(Civil_Footer_Section_2_Topics)
admin.site.register(Civil_Footer_Section_3)
admin.site.register(Civil_Footer_Section_3_Topics)
admin.site.register(Civil_Technology)
admin.site.register(Civil_Technology_Icon)
admin.site.register(Civil_Our_Services)
admin.site.register(Civil_Notice_Board)
admin.site.register(Civil_Order_Card)
admin.site.register(Civil_Security_Page)
admin.site.register(Civil_Company_Member)



admin.site.register(Civil_Live_Chat_Admin_Sound)
admin.site.register(Civil_User_Sound)
admin.site.register(Civil_User_Order_Sound)

